# Site settings
title: Diane Manière
description: "Diane Manière's personal website"
url: "http://dianemaniere.com"
baseurl: ""
profilepic: "/images/diane.jpg"
bkimage: "/images/bg.jpg"
google_analytics: G-LP83YYV3S1

author:
  name: "Diane Manière"
  email: diane.maniere@gmail.com
  twitter_username: dianemaniere
  github_username: dway8
  linkedin_username: diane-maniere
  kaggle_name: dway88

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ["README.md"]
